export const FOO_INCREMENT_ENTHUSIASM = 'FOO_INCREMENT_ENTHUSIASM';
export type FOO_INCREMENT_ENTHUSIASM = typeof FOO_INCREMENT_ENTHUSIASM;

export const FOO_DECREMENT_ENTHUSIASM = 'FOO_DECREMENT_ENTHUSIASM';
export type FOO_DECREMENT_ENTHUSIASM = typeof FOO_DECREMENT_ENTHUSIASM;

export const BAR_INCREMENT_ENTHUSIASM = 'BAR_INCREMENT_ENTHUSIASM';
export type BAR_INCREMENT_ENTHUSIASM = typeof BAR_INCREMENT_ENTHUSIASM;

export const BAR_DECREMENT_ENTHUSIASM = 'BAR_DECREMENT_ENTHUSIASM';
export type BAR_DECREMENT_ENTHUSIASM = typeof BAR_DECREMENT_ENTHUSIASM;

export const RECIPE_ADD_CATEGORY = 'RECIPE_ADD_CATEGORY';
export type RECIPE_ADD_CATEGORY = typeof RECIPE_ADD_CATEGORY;

export const RECIPE_ADD_CATEGORY_SUCCESS = 'RECIPE_ADD_CATEGORY_SUCCESS';
export type RECIPE_ADD_CATEGORY_SUCCESS = typeof RECIPE_ADD_CATEGORY_SUCCESS;

export const RECIPE_ADD_CATEGORY_FAILURE = 'RECIPE_ADD_CATEGORY_FAILURE';
export type RECIPE_ADD_CATEGORY_FAILURE = typeof RECIPE_ADD_CATEGORY_FAILURE;

export const RECIPE_CHANGE_CATEGORY_NAME = 'RECIPE_CHANGE_CATEGORY_NAME';
export type RECIPE_CHANGE_CATEGORY_NAME = typeof RECIPE_CHANGE_CATEGORY_NAME;

export const RECIPE_CHANGE_CATEGORY_DESCRIPTION = 'RECIPE_CHANGE_CATEGORY_DESCRIPTION';
export type RECIPE_CHANGE_CATEGORY_DESCRIPTION = typeof RECIPE_CHANGE_CATEGORY_DESCRIPTION;

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export type FETCH_CATEGORIES_SUCCESS = typeof FETCH_CATEGORIES_SUCCESS;

export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export type FETCH_CATEGORIES_FAILURE = typeof FETCH_CATEGORIES_FAILURE;

export const RECIPE_ADD_RECIPE = 'RECIPE_ADD_RECIPE ';
export type RECIPE_ADD_RECIPE  = typeof RECIPE_ADD_RECIPE;

export const RECIPE_CHANGE_RECIPE_NAME = 'RECIPE_CHANGE_RECIPE_NAME';
export type RECIPE_CHANGE_RECIPE_NAME = typeof RECIPE_CHANGE_RECIPE_NAME;

export const RECIPE_CHANGE_RECIPE_URL = 'RECIPE_CHANGE_RECIPE_URL';
export type RECIPE_CHANGE_RECIPE_URL= typeof RECIPE_CHANGE_RECIPE_URL;

export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export type FETCH_RECIPES_SUCCESS = typeof FETCH_RECIPES_SUCCESS;

export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';
export type FETCH_RECIPES_FAILURE = typeof FETCH_RECIPES_FAILURE;
