export const FOO_INCREMENT_ENTHUSIASM = 'FOO_INCREMENT_ENTHUSIASM';
export type FOO_INCREMENT_ENTHUSIASM = typeof FOO_INCREMENT_ENTHUSIASM;

export const FOO_DECREMENT_ENTHUSIASM = 'FOO_DECREMENT_ENTHUSIASM';
export type FOO_DECREMENT_ENTHUSIASM = typeof FOO_DECREMENT_ENTHUSIASM;

export const BAR_INCREMENT_ENTHUSIASM = 'BAR_INCREMENT_ENTHUSIASM';
export type BAR_INCREMENT_ENTHUSIASM = typeof BAR_INCREMENT_ENTHUSIASM;

export const BAR_DECREMENT_ENTHUSIASM = 'BAR_DECREMENT_ENTHUSIASM';
export type BAR_DECREMENT_ENTHUSIASM = typeof BAR_DECREMENT_ENTHUSIASM;

export const RECIPE_ADD_CATEGORY = 'RECIPE_ADD_CATEGORY';
export type RECIPE_ADD_CATEGORY = typeof RECIPE_ADD_CATEGORY;